-- CreateEnum
CREATE TYPE "AiPlatform" AS ENUM ('chatgpt', 'perplexity', 'google_ai', 'gemini', 'copilot');

-- CreateEnum
CREATE TYPE "SentimentType" AS ENUM ('positive', 'neutral', 'negative');

-- CreateEnum
CREATE TYPE "DirectoryPlatform" AS ENUM ('google', 'yelp', 'foursquare', 'bing', 'apple_maps', 'facebook');

-- CreateEnum
CREATE TYPE "OnboardingStatus" AS ENUM ('scan_complete', 'setup_pending', 'setup_complete', 'active');

-- CreateEnum
CREATE TYPE "Plan" AS ENUM ('free_scan', 'starter', 'growth');

-- CreateEnum
CREATE TYPE "FileType" AS ENUM ('llms_txt', 'schema_json');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,
    "hashedPassword" TEXT,
    "role" TEXT NOT NULL DEFAULT 'user',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL,
    "businessName" TEXT NOT NULL,
    "websiteUrl" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "category" TEXT,
    "services" TEXT[],
    "hours" TEXT,
    "googleBusinessUrl" TEXT,
    "onboardingStatus" "OnboardingStatus" NOT NULL DEFAULT 'scan_complete',
    "plan" "Plan" NOT NULL DEFAULT 'free_scan',
    "stripeCustomerId" TEXT,
    "stripeSubscriptionId" TEXT,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Client_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Query" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "queryText" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Query_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Citation" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "queryId" TEXT NOT NULL,
    "platform" "AiPlatform" NOT NULL,
    "cited" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER,
    "sentiment" "SentimentType",
    "rawResponse" TEXT,
    "sourcesCited" JSONB NOT NULL DEFAULT '[]',
    "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Citation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VisibilityScore" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "score" INTEGER NOT NULL,
    "queryCoverage" INTEGER NOT NULL,
    "platformCoverage" INTEGER NOT NULL,
    "period" TIMESTAMP(3) NOT NULL,
    "breakdown" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VisibilityScore_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Competitor" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "competitorName" TEXT NOT NULL,
    "competitorUrl" TEXT,
    "isAutoDetected" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Competitor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CompetitorCitation" (
    "id" TEXT NOT NULL,
    "competitorId" TEXT NOT NULL,
    "queryId" TEXT NOT NULL,
    "platform" "AiPlatform" NOT NULL,
    "cited" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER,
    "rawResponse" TEXT,
    "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CompetitorCitation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NapAudit" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "platform" "DirectoryPlatform" NOT NULL,
    "nameMatch" BOOLEAN,
    "addressMatch" BOOLEAN,
    "phoneMatch" BOOLEAN,
    "listingUrl" TEXT,
    "issues" TEXT[],
    "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NapAudit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReviewSnapshot" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "platform" "DirectoryPlatform" NOT NULL,
    "rating" DOUBLE PRECISION,
    "reviewCount" INTEGER,
    "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ReviewSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GeneratedFile" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "fileType" "FileType" NOT NULL,
    "content" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GeneratedFile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IndustrySource" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "domain" TEXT NOT NULL,
    "url" TEXT,
    "citationCount" INTEGER NOT NULL DEFAULT 0,
    "platformsCiting" "AiPlatform"[],
    "period" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "IndustrySource_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AdminNote" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AdminNote_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- CreateIndex
CREATE INDEX "Client_userId_idx" ON "Client"("userId");

-- CreateIndex
CREATE INDEX "Query_clientId_idx" ON "Query"("clientId");

-- CreateIndex
CREATE INDEX "Citation_clientId_idx" ON "Citation"("clientId");

-- CreateIndex
CREATE INDEX "Citation_clientId_platform_idx" ON "Citation"("clientId", "platform");

-- CreateIndex
CREATE INDEX "Citation_queryId_idx" ON "Citation"("queryId");

-- CreateIndex
CREATE INDEX "VisibilityScore_clientId_idx" ON "VisibilityScore"("clientId");

-- CreateIndex
CREATE INDEX "VisibilityScore_clientId_period_idx" ON "VisibilityScore"("clientId", "period");

-- CreateIndex
CREATE UNIQUE INDEX "VisibilityScore_clientId_period_key" ON "VisibilityScore"("clientId", "period");

-- CreateIndex
CREATE INDEX "Competitor_clientId_idx" ON "Competitor"("clientId");

-- CreateIndex
CREATE INDEX "CompetitorCitation_competitorId_idx" ON "CompetitorCitation"("competitorId");

-- CreateIndex
CREATE INDEX "CompetitorCitation_competitorId_platform_idx" ON "CompetitorCitation"("competitorId", "platform");

-- CreateIndex
CREATE INDEX "NapAudit_clientId_idx" ON "NapAudit"("clientId");

-- CreateIndex
CREATE INDEX "NapAudit_clientId_platform_idx" ON "NapAudit"("clientId", "platform");

-- CreateIndex
CREATE INDEX "ReviewSnapshot_clientId_idx" ON "ReviewSnapshot"("clientId");

-- CreateIndex
CREATE INDEX "ReviewSnapshot_clientId_platform_idx" ON "ReviewSnapshot"("clientId", "platform");

-- CreateIndex
CREATE INDEX "GeneratedFile_clientId_idx" ON "GeneratedFile"("clientId");

-- CreateIndex
CREATE INDEX "IndustrySource_clientId_idx" ON "IndustrySource"("clientId");

-- CreateIndex
CREATE INDEX "IndustrySource_clientId_period_idx" ON "IndustrySource"("clientId", "period");

-- CreateIndex
CREATE INDEX "AdminNote_clientId_idx" ON "AdminNote"("clientId");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Client" ADD CONSTRAINT "Client_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Query" ADD CONSTRAINT "Query_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Citation" ADD CONSTRAINT "Citation_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Citation" ADD CONSTRAINT "Citation_queryId_fkey" FOREIGN KEY ("queryId") REFERENCES "Query"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VisibilityScore" ADD CONSTRAINT "VisibilityScore_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Competitor" ADD CONSTRAINT "Competitor_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CompetitorCitation" ADD CONSTRAINT "CompetitorCitation_competitorId_fkey" FOREIGN KEY ("competitorId") REFERENCES "Competitor"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CompetitorCitation" ADD CONSTRAINT "CompetitorCitation_queryId_fkey" FOREIGN KEY ("queryId") REFERENCES "Query"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NapAudit" ADD CONSTRAINT "NapAudit_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReviewSnapshot" ADD CONSTRAINT "ReviewSnapshot_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeneratedFile" ADD CONSTRAINT "GeneratedFile_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IndustrySource" ADD CONSTRAINT "IndustrySource_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AdminNote" ADD CONSTRAINT "AdminNote_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
