import { PrismaClient } from "@prisma/client/default";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Create test user
  const hashedPassword = await bcrypt.hash("password123", 12);

  const user = await prisma.user.upsert({
    where: { email: "test@geo.com" },
    update: {},
    create: {
      email: "test@geo.com",
      name: "Test User",
      hashedPassword,
      role: "user",
    },
  });

  console.log(`Created user: ${user.email} (${user.id})`);

  // Create test client
  const client = await prisma.client.upsert({
    where: { id: "seed-client-001" },
    update: {},
    create: {
      id: "seed-client-001",
      businessName: "Joe's Coffee Shop",
      websiteUrl: "https://joescoffeeshop.com",
      city: "Austin",
      state: "TX",
      phone: "(512) 555-0123",
      address: "123 Main St, Austin, TX 78701",
      category: "Coffee Shop",
      services: ["Espresso", "Cold Brew", "Pastries", "Catering"],
      hours: "Mon-Fri 6am-6pm, Sat-Sun 7am-4pm",
      onboardingStatus: "scan_complete",
      plan: "free_scan",
      userId: user.id,
    },
  });

  console.log(`Created client: ${client.businessName} (${client.id})`);

  // Create sample queries
  const queries = [
    "best coffee shops in Austin TX",
    "where to get espresso near downtown Austin",
    "Austin coffee shops with catering services",
  ];

  for (const queryText of queries) {
    const query = await prisma.query.create({
      data: {
        clientId: client.id,
        queryText,
        isAutoGenerated: true,
        active: true,
      },
    });
    console.log(`Created query: "${query.queryText}"`);
  }

  console.log("Seeding complete.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
