// Engine I/O types — DB model types are generated by Prisma (@prisma/client)

export interface CrawlResult {
  businessName: string;
  category: string | null;
  city: string | null;
  state: string | null;
  phone: string | null;
  address: string | null;
  services: string[];
  hours: string | null;
  description: string | null;
  about: string | null;
  keyPages: { title: string; url: string }[];
  rawContent: string;
}

export interface CitationResult {
  cited: boolean;
  position: number | null;
  sentiment: "positive" | "neutral" | "negative" | null;
  rawResponse: string;
  sourcesCited: { domain: string; url: string | null }[];
}

export interface ScoreBreakdown {
  queryCoverage: number;
  platformCoverage: number;
  positionQuality: number;
  setupComplete: number;
  total: number;
}

export interface ScanResult {
  score: number;
  breakdown: ScoreBreakdown;
  platforms: {
    platform: string;
    queriesChecked: number;
    citedCount: number;
  }[];
  queries: {
    query: string;
    results: {
      platform: string;
      cited: boolean;
      position: number | null;
    }[];
  }[];
  topSources: { domain: string; citationCount: number }[];
  competitor: { name: string; url: string | null } | null;
  businessInfo: {
    name: string;
    category: string | null;
    city: string | null;
  };
}

export interface RobotsTxtAudit {
  accessible: boolean;
  blocked: string[];
  total: number;
  status: "clean" | "blocked" | "no_robots_txt";
}

export interface NameMatchResult {
  cited: boolean;
  position: number | null;
}

export interface ExtractedSource {
  domain: string;
  url: string | null;
}

export interface ApiResponse<T> {
  data?: T;
  error?: string;
}

// --- NAP / Directory Engine Types ---

export interface NapCheckResult {
  platform: string;
  nameMatch: boolean | null;
  addressMatch: boolean | null;
  phoneMatch: boolean | null;
  listingUrl?: string;
  issues: string[];
}

export interface ReviewPullResult {
  platform: string;
  rating: number | null;
  reviewCount: number | null;
  url?: string;
}

// --- Competitor Detection Types ---

export interface DetectedCompetitor {
  name: string;
  domain?: string;
  citedInQueries: string[];
  platforms: string[];
}

// --- Recommendation Types ---

export type RecommendationSeverity = "critical" | "important" | "suggestion";

export interface Recommendation {
  id: string;
  severity: RecommendationSeverity;
  title: string;
  description: string;
  actionUrl?: string;
}

// --- Monthly Check Types ---

export interface MonthlyCheckResult {
  clientId: string;
  newScore: number;
  previousScore: number | null;
  delta: number;
  filesRegenerated: boolean;
  citationsChecked: number;
}
