import { NextRequest, NextResponse } from "next/server";
import { z } from "zod/v4";
import { requireAuth } from "@/lib/auth-utils";
import { rateLimit } from "@/lib/rate-limit";
import { runFreeScan } from "@/lib/pipelines/free-scan";
import { prisma } from "@/lib/db";
import { TimeoutError } from "@/lib/utils";
import { isBlockedUrl } from "@/lib/url-validation";
import type { ApiResponse, ScanResult } from "@/types";
import type { AiPlatform } from "@/types/platforms";

const scanSchema = z.object({
  url: z
    .string()
    .transform((val) => {
      const trimmed = val.trim();
      return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
    })
    .pipe(z.url("Must be a valid URL")),
});

const ONE_HOUR_MS = 60 * 60 * 1000;
const checkRateLimit = rateLimit({ interval: ONE_HOUR_MS, limit: 5 });

export const maxDuration = 60;

export async function POST(
  request: NextRequest
): Promise<NextResponse<ApiResponse<ScanResult>>> {
  const auth = await requireAuth();
  if (auth.error) return auth.error;

  const userId = auth.session.user.id;

  // Parse and validate body
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = scanSchema.safeParse(body);
  if (!parsed.success) {
    const message = parsed.error.issues[0]?.message ?? "Invalid input";
    return NextResponse.json({ error: message }, { status: 400 });
  }

  // Rate limit by user ID
  const { success, remaining } = await checkRateLimit(userId);
  if (!success) {
    return NextResponse.json(
      { error: "Rate limit exceeded. Try again later." },
      {
        status: 429,
        headers: {
          "Retry-After": "3600",
          "X-RateLimit-Remaining": String(remaining),
        },
      }
    );
  }

  // SSRF protection
  if (isBlockedUrl(parsed.data.url)) {
    return NextResponse.json(
      { error: "Please enter a public website URL." },
      { status: 400 }
    );
  }

  // Run the free scan pipeline
  let result: ScanResult;
  try {
    result = await runFreeScan(parsed.data.url);
  } catch (error) {
    if (error instanceof TimeoutError) {
      return NextResponse.json(
        { error: "Scan timed out. Please try again." },
        { status: 504 }
      );
    }

    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    console.error("[POST /api/dashboard/scan] Pipeline error:", errorMessage);

    const userMessage = errorMessage.includes("is not configured")
      ? "Service configuration error. Please contact support."
      : "Scan failed. Please try again later.";

    return NextResponse.json({ error: userMessage }, { status: 500 });
  }

  // Persist results to database
  let persisted = true;
  let reportId: string | undefined;
  let clientId: string | undefined;
  try {
    const ids = await persistScanResults(userId, parsed.data.url, result);
    reportId = ids.reportId;
    clientId = ids.clientId;
  } catch (error) {
    persisted = false;
    const msg = error instanceof Error ? error.message : "Unknown error";
    console.error("[POST /api/dashboard/scan] Failed to persist results:", msg);
  }

  return NextResponse.json(
    { data: result, persisted, reportId, clientId },
    { headers: { "X-RateLimit-Remaining": String(remaining) } }
  );
}

async function persistScanResults(
  userId: string,
  url: string,
  result: ScanResult
): Promise<{ reportId: string; clientId: string }> {
  // Find an existing free_scan client for this user, or create one.
  // Paid clients are never touched — each paid subscription is a separate client.
  // Serializable isolation prevents two concurrent requests from both seeing
  // no existing free_scan client and each creating a duplicate.
  const client = await prisma.$transaction(async (tx) => {
    const existing = await tx.client.findFirst({
      where: { userId, plan: "free_scan" },
      orderBy: { createdAt: "desc" },
    });

    if (existing) {
      return tx.client.update({
        where: { id: existing.id },
        data: {
          websiteUrl: url,
          businessName: result.businessInfo.name,
          city: result.businessInfo.city ?? existing.city,
          category: result.businessInfo.category ?? existing.category,
        },
      });
    }

    return tx.client.create({
      data: {
        userId,
        websiteUrl: url,
        businessName: result.businessInfo.name,
        city: result.businessInfo.city ?? "Unknown",
        category: result.businessInfo.category,
        plan: "free_scan",
        onboardingStatus: "scan_complete",
      },
    });
  }, { isolationLevel: "Serializable" });

  const clientId = client.id;

  // Delete old auto-generated queries (and their cascading citations) before inserting fresh results
  await prisma.query.deleteMany({
    where: { clientId, isAutoGenerated: true },
  });

  // Create query and citation records (batch citations per query)
  for (const queryResult of result.queries) {
    const query = await prisma.query.create({
      data: {
        clientId,
        queryText: queryResult.query,
        isAutoGenerated: true,
      },
    });

    if (queryResult.results.length > 0) {
      await prisma.citation.createMany({
        data: queryResult.results.map((p) => ({
          clientId,
          queryId: query.id,
          platform: p.platform as AiPlatform,
          cited: p.cited,
          position: p.position,
        })),
      });
    }
  }

  // Save visibility score
  const now = new Date();
  const period = new Date(now.getFullYear(), now.getMonth(), 1);
  const breakdownJson = JSON.parse(JSON.stringify(result.breakdown));

  await prisma.visibilityScore.upsert({
    where: {
      clientId_period: { clientId, period },
    },
    update: {
      score: result.score,
      queryCoverage: result.breakdown.queryCoverage,
      platformCoverage: result.breakdown.platformCoverage,
      breakdown: breakdownJson,
    },
    create: {
      clientId,
      score: result.score,
      queryCoverage: result.breakdown.queryCoverage,
      platformCoverage: result.breakdown.platformCoverage,
      period,
      breakdown: breakdownJson,
    },
  });

  // Save a snapshot of the full scan result as a report
  const report = await prisma.scanReport.create({
    data: {
      clientId,
      url,
      score: result.score,
      data: JSON.parse(JSON.stringify(result)),
    },
  });

  return { reportId: report.id, clientId };
}
